### ISSUE TITLE
local.css

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_little-fuzzy#2]
`abbr.initialism` and `abbr.degree` are not necessary here. (Was this in the semantics manual somewhere?)

Space and indent `abbr.name` like other elements (i.e. not on one line)

No space after selector/before brackets

**Comment by acabal** [comment]
abbr.era is necessary with style `font-variant: all-small-caps`; see https://standardebooks.org/contribute/typography#latinisms

**Comment by drgrigg** [comment]
Not sure that I understand your statement that abbr.initialism and abbr.degree not necessary. In an email, you said:

"6. If you have `abbr.name` then you need `abbr.name{ white-space: nowrap; }` in local.css"

I use both class="initialism" and class="degree" in the text.

**Comment by acabal** [comment]
Right; I said if you have `abbr.name`.  I didn't say, If you have `abbr.name` or `abbr.initialism` or `abbr.anything-else` :)

Initialisms and degrees don't have white space in them to begin with, so they don't need that styling.  `abbr.name` is the only one that typically has white space (for example `<abbr class="name">H. P.</abbr> Lovecraft`, so it needs that style as [indicated here[(https://standardebooks.org/contribute/typography#initials), but the other ones don't.

**Comment by drgrigg** [comment]
Oh, OK. I thought 'name' here was just a placeholder for the class name. OK.

**Comment by drgrigg** [comment]
Done, I think.
