### ISSUE TITLE
i/em tags

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_little-fuzzy#3]
chapter-15.xhtml, lines 40 and 43 should be `<i>` not `<em>` as they are interior monologue and not emphasis.

chapter-5.xhtml, line 120: `<i>` tags need language tag, we can use a custom one prefaced with x- like `<i xml:lang="x-fuzzy">` (or whatever it should be, I haven't read the book yet)

**Comment by drgrigg** [comment]
Good, will do, I like the idea of xml:lang="x-fuzzy"!  The particular reference you point to, however, is the Khoogra language, so I've invented xml:lang="x-khoogra".

But one or two spots are slightly tricky.

For example, when one of the fuzzies, in great excitement, calls out "Pa-pee Jaaak!" (their pronunciation of "Pappy Jack", so basically actually English, just excited) I think this should be surrounded with <em> tags, whereas the statement which follows IS in the fuzzy language and so gets the <i xml:lang...> tag. 

Ditto for <em> tags when the crowd of fuzzies is shouting out "Pa-pee Jaaak, Pa-pee Jaaak!"

Anyway, I've changed the text assuming my interpretation above is correct, but I am leaving this issue open.
